---
name: CheckOV
on: [push]

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          quiet: true # optional: display only failed checks
          soft_fail: true # optional: do not return an error code if there are failed checks
          framework: terraform
          download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
          #output_format: json # optional: the output format, one of: cli, json, junitxml, github_failed_only
